### ISSUE TITLE
PR body can be null

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/github_rest_api#4]
Isn't currently handled as null being possible.

**Comment by SeanTAllen** [comment]
I wonder if the proper way to deal with this for some things like body would be to have a JsonExtractor methods that gives you a String or an empty String. At least for some things like PR body (and according to @mfelsche this also can happen for Issue body).

I think there are some fields of various objects where `| None` makes sense and others where we should seriously consider things like "empty string" if it has no negative impact on using the API and provides for some ergonomics.

**Comment by mfelsche** [comment]
One possible issue of a PR / Issue body defaulting to `""` instead of being `(String | None)`, is that, depending on how the API works, a `PATCH` with an issue loaded via search or `GET` might not be idempotent, it would change `null` to `""`. While the Github UI might not even make a difference here, and I think this is tolerable in this context, is doesn't seem 100% correct and might have some unwanted side effects.

For reference, here is the openapi spec with the issue body defined as `nullable`: 

https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml Line 42858

**Comment by mfelsche** [comment]
I would also go with the second option.
While a type like `(String | None )` would be most idiomatic, the part of doing a `get_or_else` operation with this is a bit unintuitive. I once did a sketch around this and i am not 100% satisfied: https://github.com/mfelsche/pony-maybe/blob/master/maybe/maybe.pony#L6

My proposal would be to create a class `IssueBody` (or similar) and have it wrap the `(String | None)` and expose an API there for getting and setting the String.

**Comment by mfelsche** [comment]
To make sure, I understand you correctly, did you have something like this in mind: https://playground.ponylang.io/?gist=5cad35a5006e057216d7cb408c9d2770

The `Issue.body` field would then become a `class Option[T]`?

**Comment by SeanTAllen** [comment]
@mfelsche that is inline with the vague handwave I have at the moment for things that could be null.

**Comment by mfelsche** [comment]
If this is fine with you, I can apply this proposal to the PR and Issue bodies in my PR #3

**Comment by SeanTAllen** [comment]
@mfelsche i'm not sure how I feel about it, but I would be interested in seeing what it would look like for #3 and we could discuss what we like/don't like about it. Perhaps merge, perhaps revisit.

**Comment by SeanTAllen** [comment]
@mfelsche I've been thinking about this more and maybe (String | None) is best with:

```
Iter.maybe(issue.body).next_or("")
```

at the call site in examples. It is pretty straight forward and leverages the standard library.
